[tool.poetry]
name = "flatclicker"
version = "0.1.0"
description = ""
authors = ["bambi <krystian.figiel@smcebi.edu.pl>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pyautogui = "^0.9.54"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
